# Generated by Django 2.1.7 on 2019-02-23 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_status', models.BooleanField(default=False)),
                ('phone', models.TextField(max_length=15)),
                ('points', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='institution_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=15)),
                ('email_status', models.BooleanField(default=False)),
                ('account_holder', models.TextField(max_length=100)),
                ('account_number', models.TextField(max_length=200)),
                ('ifsc', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=100, null=True)),
                ('title', models.TextField(max_length=1000)),
                ('body', models.TextField(max_length=2000)),
                ('is_satisfied', models.BooleanField(default=False)),
            ],
        ),
    ]
