# Generated by Django 2.1.7 on 2019-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20190223_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
